import { BoardTheme, ArrowSkin, TrailVfx } from '../types';

export const BOARD_THEMES: BoardTheme[] = [
  {
    id: 'eye_comfort',
    name: 'Eye Comfort (Paper)',
    price: 0,
    description: 'Warm natural parchment with soothing contrast arrows matching Amaze GO.',
    bgGradient: 'from-amber-50 via-stone-100 to-amber-50',
    boardBg: 'bg-[#fcf7ee] border-[#dfd5c5] shadow-2xl shadow-stone-900/10',
    gridColor: 'border-[#eae0d2]',
    borderColor: 'border-[#d4c5b0]',
    accentColor: '#8c6544',
    previewColor: '#fcf7ee',
    tag: 'FEATURED',
    isLight: true,
  },
  {
    id: 'classic',
    name: 'Classic Slate',
    price: 0,
    description: 'Clean dark titanium slate with subtle blueprint grid.',
    bgGradient: 'from-slate-950 via-slate-900 to-slate-950',
    boardBg: 'bg-slate-900/90 border-slate-800 shadow-2xl shadow-slate-950/80',
    gridColor: 'border-slate-800/60',
    borderColor: 'border-slate-700/60',
    accentColor: '#38bdf8',
    previewColor: '#0f172a',
  },
  {
    id: 'neon',
    name: 'Neon Cyber',
    price: 250,
    description: 'Electric violet grid with laser-illuminated borders.',
    bgGradient: 'from-purple-950 via-slate-950 to-indigo-950',
    boardBg: 'bg-slate-950/90 border-fuchsia-500/40 shadow-2xl shadow-fuchsia-500/20',
    gridColor: 'border-fuchsia-900/40',
    borderColor: 'border-fuchsia-500/60',
    accentColor: '#d946ef',
    previewColor: '#2e1065',
    tag: 'POPULAR',
  },
  {
    id: 'galaxy',
    name: 'Galaxy Void',
    price: 400,
    description: 'Deep cosmic nebula with celestial starlight glow.',
    bgGradient: 'from-indigo-950 via-purple-950 to-slate-950',
    boardBg: 'bg-indigo-950/80 border-indigo-500/30 shadow-2xl shadow-indigo-500/30',
    gridColor: 'border-indigo-800/40',
    borderColor: 'border-indigo-400/50',
    accentColor: '#818cf8',
    previewColor: '#1e1b4b',
  },
  {
    id: 'lava',
    name: 'Lava Forge',
    price: 450,
    description: 'Molten magma cracks with smoldering amber warmth.',
    bgGradient: 'from-stone-950 via-red-950 to-orange-950',
    boardBg: 'bg-stone-950/90 border-orange-600/40 shadow-2xl shadow-orange-600/20',
    gridColor: 'border-red-950/60',
    borderColor: 'border-orange-500/60',
    accentColor: '#f97316',
    previewColor: '#451a03',
  },
  {
    id: 'ice',
    name: 'Glacial Ice',
    price: 500,
    description: 'Frosty sub-zero crystalline tiles with arctic aura.',
    bgGradient: 'from-sky-950 via-slate-950 to-cyan-950',
    boardBg: 'bg-sky-950/70 border-cyan-400/40 shadow-2xl shadow-cyan-400/20',
    gridColor: 'border-cyan-900/40',
    borderColor: 'border-cyan-400/60',
    accentColor: '#22d3ee',
    previewColor: '#083344',
  },
  {
    id: 'forest',
    name: 'Emerald Forest',
    price: 550,
    description: 'Lush evergreen canopy with bio-luminescent moss accents.',
    bgGradient: 'from-emerald-950 via-slate-950 to-teal-950',
    boardBg: 'bg-emerald-950/80 border-emerald-500/40 shadow-2xl shadow-emerald-500/20',
    gridColor: 'border-emerald-900/40',
    borderColor: 'border-emerald-400/60',
    accentColor: '#10b981',
    previewColor: '#064e3b',
  },
  {
    id: 'cyber',
    name: 'Cyber Matrix',
    price: 600,
    description: 'Digital wireframes with cascading data stream luminescence.',
    bgGradient: 'from-slate-950 via-green-950/50 to-slate-950',
    boardBg: 'bg-black/90 border-green-500/40 shadow-2xl shadow-green-500/20',
    gridColor: 'border-green-900/40',
    borderColor: 'border-green-400/60',
    accentColor: '#4ade80',
    previewColor: '#052e16',
  },
  {
    id: 'space',
    name: 'Deep Space',
    price: 650,
    description: 'Infinite cosmic dark matter framed by stellar constellations.',
    bgGradient: 'from-slate-950 via-blue-950 to-slate-950',
    boardBg: 'bg-slate-950/90 border-blue-600/40 shadow-2xl shadow-blue-600/20',
    gridColor: 'border-blue-950',
    borderColor: 'border-blue-500/60',
    accentColor: '#3b82f6',
    previewColor: '#172554',
  },
  {
    id: 'candy',
    name: 'Candy Sweet',
    price: 700,
    description: 'Playful pastel dreamscape with bubblegum sweetness.',
    bgGradient: 'from-pink-950 via-purple-950 to-rose-950',
    boardBg: 'bg-pink-950/70 border-pink-400/40 shadow-2xl shadow-pink-400/20',
    gridColor: 'border-pink-900/40',
    borderColor: 'border-pink-300/60',
    accentColor: '#f472b6',
    previewColor: '#500724',
  },
  {
    id: 'gold',
    name: 'Royal Gold',
    price: 900,
    description: 'Prestigious 24k gilded frame for puzzle grandmasters.',
    bgGradient: 'from-amber-950 via-stone-950 to-yellow-950',
    boardBg: 'bg-stone-950/90 border-amber-400/60 shadow-2xl shadow-amber-400/30',
    gridColor: 'border-amber-950/70',
    borderColor: 'border-yellow-400/80',
    accentColor: '#fbbf24',
    previewColor: '#451a03',
    tag: 'LEGENDARY',
  },
  {
    id: 'futuristic',
    name: 'Quantum Holo',
    price: 1200,
    description: 'Next-gen anti-gravity interface with quantum flux containment.',
    bgGradient: 'from-teal-950 via-slate-950 to-cyan-950',
    boardBg: 'bg-slate-950/90 border-cyan-300/60 shadow-2xl shadow-cyan-300/30',
    gridColor: 'border-cyan-950',
    borderColor: 'border-teal-300/80',
    accentColor: '#2dd4bf',
    previewColor: '#042f2e',
    tag: 'ELITE',
  },
  {
    id: 'sakura',
    name: 'Sakura Garden',
    price: 650,
    description: 'Peaceful Japanese cherry blossom courtyard with soft petal breezes.',
    bgGradient: 'from-rose-950 via-slate-950 to-pink-950',
    boardBg: 'bg-rose-950/70 border-pink-400/40 shadow-2xl shadow-rose-400/20',
    gridColor: 'border-pink-900/30',
    borderColor: 'border-pink-300/60',
    accentColor: '#fb7185',
    previewColor: '#4c0519',
    tag: 'ZEN',
  },
  {
    id: 'steampunk',
    name: 'Clockwork Foundry',
    price: 850,
    description: 'Industrial Victorian copper & brass mechanisms with spinning gears.',
    bgGradient: 'from-amber-950 via-stone-950 to-orange-950',
    boardBg: 'bg-stone-950/90 border-amber-600/40 shadow-2xl shadow-amber-600/25',
    gridColor: 'border-amber-900/40',
    borderColor: 'border-amber-500/60',
    accentColor: '#d97706',
    previewColor: '#451a03',
    tag: 'ANTIQUE',
  },
  {
    id: 'desert_dunes',
    name: 'Sahara Mirage',
    price: 500,
    description: 'Golden sunlit sand dunes with warm desert breeze ripples.',
    bgGradient: 'from-yellow-950 via-stone-950 to-amber-950',
    boardBg: 'bg-stone-950/85 border-amber-500/40 shadow-2xl shadow-amber-500/20',
    gridColor: 'border-amber-900/30',
    borderColor: 'border-yellow-600/60',
    accentColor: '#f59e0b',
    previewColor: '#78350f',
  },
];

export const ARROW_SKINS: ArrowSkin[] = [
  // ---------------- PAGE 1 (Items 1 to 10) ----------------
  {
    id: 'eye_comfort_arrow',
    name: 'Garden Garter 🌿',
    price: 0,
    description: 'Gentle nature snake with warm earthy olive scales and friendly amber eyes.',
    bodyGradient: 'from-amber-800 to-stone-800',
    glowColor: 'rgba(140, 101, 68, 0.4)',
    iconColor: '#ffffff',
    accentColor: '#8c6544',
    secondaryColor: '#65a30d',
    previewColor: '#8c6544',
    tag: 'STARTER',
    snakeStyle: 'garter',
    headIcon: '🌿',
    patternType: 'stripes',
    eyeColor: '#fde047',
    tongueColor: '#ef4444',
    bgBiome: 'jungle',
    rarity: 'Starter',
    eyeCount: 2,
    bodyThickness: 'regular',
  },
  {
    id: 'classic',
    name: 'Azure Corn Snake 💧',
    price: 0,
    description: 'Vibrant sky-blue serpent with sleek aerodynamic scales and bright eyes.',
    bodyGradient: 'from-sky-500 to-blue-600',
    glowColor: 'rgba(56, 189, 248, 0.4)',
    iconColor: '#ffffff',
    accentColor: '#38bdf8',
    secondaryColor: '#1d4ed8',
    previewColor: '#0284c7',
    tag: 'STARTER',
    snakeStyle: 'python',
    headIcon: '💧',
    patternType: 'scales',
    eyeColor: '#ffffff',
    tongueColor: '#f43f5e',
    bgBiome: 'ocean',
    rarity: 'Starter',
    eyeCount: 2,
    bodyThickness: 'regular',
  },
  {
    id: 'pink_bubblegum',
    name: 'Sakura Bubblegum 💖',
    price: 1999,
    description: 'Completely vivid pink in color! Neon rose body, candy pink eyes, and sweet pink aura.',
    bodyGradient: 'from-pink-400 via-rose-500 to-fuchsia-500',
    glowColor: 'rgba(244, 114, 182, 0.7)',
    iconColor: '#ffffff',
    accentColor: '#ec4899',
    secondaryColor: '#f472b6',
    previewColor: '#ec4899',
    tag: 'ALL PINK',
    snakeStyle: 'sakura',
    headIcon: '💖',
    patternType: 'petals',
    eyeColor: '#fdf2f8',
    tongueColor: '#f43f5e',
    bgBiome: 'candy',
    rarity: 'Starter',
    eyeCount: 2,
    bodyThickness: 'regular',
  },
  {
    id: 'gummy',
    name: 'Gummy Jelly Worm 🍬',
    price: 2499,
    description: 'Chubby, extra-thick bouncy cherry-lime gummy worm with glistening sugar shine.',
    bodyGradient: 'from-rose-400 via-pink-500 to-lime-400',
    glowColor: 'rgba(244, 63, 94, 0.5)',
    iconColor: '#ffffff',
    accentColor: '#f43f5e',
    secondaryColor: '#84cc16',
    previewColor: '#f43f5e',
    tag: 'CHUBBY',
    snakeStyle: 'gummy',
    headIcon: '🍬',
    patternType: 'rings',
    eyeColor: '#ffffff',
    tongueColor: '#fbbf24',
    bgBiome: 'candy',
    rarity: 'Common',
    eyeCount: 2,
    bodyThickness: 'chubby',
    strokeMultiplier: 1.35,
  },
  {
    id: 'slender_viper',
    name: 'Silver Needle Viper 🪡',
    price: 2999,
    description: 'Ultra-slender liquid mercury chrome serpent with needle-sharp aerodynamic agility.',
    bodyGradient: 'from-slate-200 via-slate-400 to-zinc-600',
    glowColor: 'rgba(203, 213, 225, 0.6)',
    iconColor: '#ffffff',
    accentColor: '#94a3b8',
    secondaryColor: '#38bdf8',
    previewColor: '#64748b',
    tag: 'SLENDER',
    snakeStyle: 'viper',
    headIcon: '🪡',
    patternType: 'keels',
    eyeColor: '#38bdf8',
    tongueColor: '#0ea5e9',
    bgBiome: 'cyber',
    rarity: 'Common',
    eyeCount: 2,
    bodyThickness: 'slender',
    strokeMultiplier: 0.75,
  },
  {
    id: 'crystal',
    name: 'Emerald Tree Python 🍃',
    price: 3499,
    description: 'Lush rainforest emerald snake with radiant diamond scales and jade eyes.',
    bodyGradient: 'from-emerald-400 via-teal-400 to-emerald-600',
    glowColor: 'rgba(52, 211, 153, 0.6)',
    iconColor: '#ffffff',
    accentColor: '#10b981',
    secondaryColor: '#047857',
    previewColor: '#059669',
    tag: 'POPULAR',
    snakeStyle: 'python',
    headIcon: '🍃',
    patternType: 'diamonds',
    eyeColor: '#a7f3d0',
    tongueColor: '#dc2626',
    bgBiome: 'jungle',
    rarity: 'Common',
    eyeCount: 2,
    bodyThickness: 'regular',
  },
  {
    id: 'cyclops_alien',
    name: 'Cosmic Cyclops Naga 👁️',
    price: 3999,
    description: 'Mysterious alien serpent possessing only one large, all-seeing glowing psychic eye.',
    bodyGradient: 'from-purple-500 via-indigo-600 to-cyan-500',
    glowColor: 'rgba(168, 85, 247, 0.75)',
    iconColor: '#ffffff',
    accentColor: '#a855f7',
    secondaryColor: '#06b6d4',
    previewColor: '#7e22ce',
    tag: 'ONE EYE',
    snakeStyle: 'cyclops',
    headIcon: '👁️',
    patternType: 'stars',
    eyeColor: '#22d3ee',
    tongueColor: '#d946ef',
    bgBiome: 'cosmic',
    rarity: 'Rare',
    eyeCount: 1,
    eyeType: 'single',
    bodyThickness: 'regular',
  },
  {
    id: 'golden',
    name: 'Royal Sun Cobra 👑',
    price: 4499,
    description: 'Majestic gilded cobra with flared royal hood, jeweled crown, and gold gaze.',
    bodyGradient: 'from-amber-300 via-yellow-400 to-amber-600',
    glowColor: 'rgba(251, 191, 36, 0.8)',
    iconColor: '#78350f',
    accentColor: '#f59e0b',
    secondaryColor: '#b45309',
    previewColor: '#d97706',
    tag: 'ROYAL',
    snakeStyle: 'cobra',
    headIcon: '👑',
    patternType: 'diamonds',
    eyeColor: '#78350f',
    tongueColor: '#b91c1c',
    bgBiome: 'temple',
    rarity: 'Rare',
    eyeCount: 2,
    bodyThickness: 'regular',
  },
  {
    id: 'fire',
    name: 'Inferno Fire Wyrm 🔥',
    price: 4999,
    description: 'Blazing molten serpent with flaming horns, ember scales, and fiery spine.',
    bodyGradient: 'from-amber-400 via-orange-500 to-red-600',
    glowColor: 'rgba(249, 115, 22, 0.6)',
    iconColor: '#fff7ed',
    accentColor: '#ea580c',
    secondaryColor: '#dc2626',
    previewColor: '#c2410c',
    tag: 'HOT',
    snakeStyle: 'dragon',
    headIcon: '🔥',
    patternType: 'flames',
    eyeColor: '#fef08a',
    tongueColor: '#ff0000',
    bgBiome: 'volcano',
    rarity: 'Rare',
    eyeCount: 2,
    bodyThickness: 'thick',
  },
  {
    id: 'ice',
    name: 'Frost Glacial Drake ❄️',
    price: 5999,
    description: 'Sub-zero crystalline arctic snake with icicle crown leaving frosty trails.',
    bodyGradient: 'from-cyan-300 via-sky-400 to-blue-500',
    glowColor: 'rgba(34, 211, 238, 0.6)',
    iconColor: '#f0fdf4',
    accentColor: '#06b6d4',
    secondaryColor: '#0284c7',
    previewColor: '#0284c7',
    tag: 'FROST',
    snakeStyle: 'frost',
    headIcon: '❄️',
    patternType: 'spikes',
    eyeColor: '#e0f2fe',
    tongueColor: '#38bdf8',
    bgBiome: 'arctic',
    rarity: 'Rare',
    eyeCount: 2,
    bodyThickness: 'regular',
  },

  // ---------------- PAGE 2 (Items 11 to 20) ----------------
  {
    id: 'desert',
    name: 'Horned Sand Viper 🏜️',
    price: 6499,
    description: 'Camouflaged desert predator with devilish brow horns and chevron scales.',
    bodyGradient: 'from-amber-600 via-yellow-600 to-stone-700',
    glowColor: 'rgba(217, 119, 6, 0.5)',
    iconColor: '#ffffff',
    accentColor: '#d97706',
    secondaryColor: '#78350f',
    previewColor: '#b45309',
    tag: 'WILD',
    snakeStyle: 'desert',
    headIcon: '🏜️',
    patternType: 'spots',
    eyeColor: '#fef08a',
    tongueColor: '#dc2626',
    bgBiome: 'desert',
    rarity: 'Rare',
    eyeCount: 2,
    bodyThickness: 'regular',
  },
  {
    id: 'anaconda',
    name: 'Amazon Giant Anaconda 🐊',
    price: 6999,
    description: 'Massive heavy river constrictor with deep olive hues and bold dark rosettes.',
    bodyGradient: 'from-lime-800 via-emerald-900 to-yellow-900',
    glowColor: 'rgba(101, 163, 13, 0.5)',
    iconColor: '#ffffff',
    accentColor: '#4d7c0f',
    secondaryColor: '#1c1917',
    previewColor: '#3f6212',
    tag: 'HEAVY',
    snakeStyle: 'anaconda',
    headIcon: '🐊',
    patternType: 'spots',
    eyeColor: '#f97316',
    tongueColor: '#991b1b',
    bgBiome: 'swamp',
    rarity: 'Rare',
    eyeCount: 2,
    bodyThickness: 'thick',
    strokeMultiplier: 1.15,
  },
  {
    id: 'tiger',
    name: 'Titan Tiger Boa 🐅',
    price: 7499,
    description: 'Apex jungle hunter sporting fierce amber fur tones and pitch-black tiger stripes.',
    bodyGradient: 'from-amber-500 via-orange-600 to-stone-900',
    glowColor: 'rgba(234, 88, 12, 0.6)',
    iconColor: '#ffffff',
    accentColor: '#ea580c',
    secondaryColor: '#09090b',
    previewColor: '#c2410c',
    tag: 'FIERCE',
    snakeStyle: 'python',
    headIcon: '🐅',
    patternType: 'stripes',
    eyeColor: '#fef08a',
    tongueColor: '#ef4444',
    bgBiome: 'jungle',
    rarity: 'Rare',
    eyeCount: 2,
    bodyThickness: 'regular',
  },
  {
    id: 'neon',
    name: 'Coral Neon Viper 🌺',
    price: 8499,
    description: 'High-voltage electric magenta viper with fluorescent neon ring bands.',
    bodyGradient: 'from-fuchsia-500 to-pink-600',
    glowColor: 'rgba(217, 70, 239, 0.6)',
    iconColor: '#ffffff',
    accentColor: '#f43f5e',
    secondaryColor: '#d946ef',
    previewColor: '#c026d3',
    snakeStyle: 'viper',
    headIcon: '🌺',
    patternType: 'rings',
    eyeColor: '#22d3ee',
    tongueColor: '#ec4899',
    bgBiome: 'ocean',
    rarity: 'Rare',
    eyeCount: 2,
    bodyThickness: 'regular',
  },
  {
    id: 'cactus',
    name: 'Prickly Saguaro Viper 🌵',
    price: 9999,
    description: 'Desert succulent serpent with spiky needle ridges and a blooming golden flower crown.',
    bodyGradient: 'from-emerald-600 via-green-700 to-teal-800',
    glowColor: 'rgba(34, 197, 94, 0.6)',
    iconColor: '#ffffff',
    accentColor: '#16a34a',
    secondaryColor: '#eab308',
    previewColor: '#15803d',
    tag: 'SPINY',
    snakeStyle: 'cactus',
    headIcon: '🌵',
    patternType: 'thorns',
    eyeColor: '#fef08a',
    tongueColor: '#e11d48',
    bgBiome: 'desert',
    rarity: 'Rare',
    eyeCount: 2,
    bodyThickness: 'regular',
  },
  {
    id: 'lightning',
    name: 'Thunderbolt Mamba ⚡',
    price: 0,
    description: 'Electrified supersonic serpent with static plasma arcs and yellow glow.',
    bodyGradient: 'from-yellow-300 via-amber-400 to-yellow-600',
    glowColor: 'rgba(250, 204, 21, 0.7)',
    iconColor: '#ffffff',
    accentColor: '#eab308',
    secondaryColor: '#ca8a04',
    previewColor: '#ca8a04',
    tag: '10 ADS',
    unlockType: 'ads',
    adsRequired: 10,
    snakeStyle: 'electric',
    headIcon: '⚡',
    patternType: 'stripes',
    eyeColor: '#fef9c3',
    tongueColor: '#ef4444',
    bgBiome: 'cyber',
    rarity: 'Epic',
    eyeCount: 2,
    bodyThickness: 'slender',
  },
  {
    id: 'albino',
    name: 'Albino Blossom Boa 🌸',
    price: 0,
    description: 'Rare angelic white & sakura pink constrictor with jewel ruby eyes and blossom crown.',
    bodyGradient: 'from-rose-200 via-pink-300 to-rose-400',
    glowColor: 'rgba(251, 113, 133, 0.6)',
    iconColor: '#ffffff',
    accentColor: '#fb7185',
    secondaryColor: '#f43f5e',
    previewColor: '#f43f5e',
    tag: '10 ADS',
    unlockType: 'ads',
    adsRequired: 10,
    snakeStyle: 'sakura',
    headIcon: '🌸',
    patternType: 'petals',
    eyeColor: '#e11d48',
    tongueColor: '#f43f5e',
    bgBiome: 'sakura',
    rarity: 'Epic',
    eyeCount: 2,
    bodyThickness: 'regular',
  },
  {
    id: 'toxic',
    name: 'Toxic Biohazard Hydra ☣️',
    price: 0,
    description: 'Radioactive neon mutant with glowing acid fangs and warning biohazard markings.',
    bodyGradient: 'from-lime-400 via-green-500 to-emerald-700',
    glowColor: 'rgba(132, 204, 22, 0.8)',
    iconColor: '#ffffff',
    accentColor: '#84cc16',
    secondaryColor: '#15803d',
    previewColor: '#65a30d',
    tag: '10 ADS',
    unlockType: 'ads',
    adsRequired: 10,
    snakeStyle: 'toxic',
    headIcon: '☣️',
    patternType: 'spots',
    eyeColor: '#facc15',
    tongueColor: '#a3e635',
    bgBiome: 'toxic',
    rarity: 'Epic',
    eyeCount: 2,
    bodyThickness: 'regular',
  },
  {
    id: 'galaxy',
    name: 'Cosmic Void Serpent 🌌',
    price: 0,
    description: 'Stellar astral serpent forged from supernova stardust and dark matter nebulas.',
    bodyGradient: 'from-indigo-400 via-purple-500 to-pink-500',
    glowColor: 'rgba(168, 85, 247, 0.6)',
    iconColor: '#ffffff',
    accentColor: '#a855f7',
    secondaryColor: '#6366f1',
    previewColor: '#7e22ce',
    tag: '10 ADS',
    unlockType: 'ads',
    adsRequired: 10,
    snakeStyle: 'void',
    headIcon: '🌌',
    patternType: 'stars',
    eyeColor: '#fdf4ff',
    tongueColor: '#d946ef',
    bgBiome: 'cosmic',
    rarity: 'Epic',
    eyeCount: 2,
    bodyThickness: 'regular',
  },
  {
    id: 'robot',
    name: 'Cyber Mecha Serpent 🤖',
    price: 0,
    description: 'Titanium plating with cybernetic neon laser optic visor and circuit traces.',
    bodyGradient: 'from-slate-300 via-slate-500 to-zinc-700',
    glowColor: 'rgba(56, 189, 248, 0.6)',
    iconColor: '#38bdf8',
    accentColor: '#38bdf8',
    secondaryColor: '#0f172a',
    previewColor: '#475569',
    tag: '10 ADS',
    unlockType: 'ads',
    adsRequired: 10,
    snakeStyle: 'cyber',
    headIcon: '🤖',
    patternType: 'cyber',
    eyeColor: '#38bdf8',
    tongueColor: '#00f0ff',
    bgBiome: 'cyber',
    rarity: 'Epic',
    eyeCount: 2,
    bodyThickness: 'thick',
  },

  // ---------------- PAGE 3 (Items 21 to 25) ----------------
  {
    id: 'ocean',
    name: 'Deep Sea Leviathan 🌊',
    price: 0,
    description: 'Abyssal deep ocean serpent with spined aquatic dorsal fins and bioluminescent lure.',
    bodyGradient: 'from-cyan-500 via-teal-700 to-slate-900',
    glowColor: 'rgba(6, 182, 212, 0.7)',
    iconColor: '#ffffff',
    accentColor: '#06b6d4',
    secondaryColor: '#0f172a',
    previewColor: '#0e7490',
    tag: '10 ADS',
    unlockType: 'ads',
    adsRequired: 10,
    snakeStyle: 'basilisk',
    headIcon: '🌊',
    patternType: 'spikes',
    eyeColor: '#a5f3fc',
    tongueColor: '#22d3ee',
    bgBiome: 'ocean',
    rarity: 'Epic',
    eyeCount: 2,
    bodyThickness: 'thick',
  },
  {
    id: 'steampunk',
    name: 'Clockwork Brass Naga ⚙️',
    price: 0,
    description: 'Victorian clockwork automaton made of polished bronze gears and steam gauge dial eyes.',
    bodyGradient: 'from-amber-600 via-yellow-700 to-stone-800',
    glowColor: 'rgba(217, 119, 6, 0.7)',
    iconColor: '#ffffff',
    accentColor: '#b45309',
    secondaryColor: '#78350f',
    previewColor: '#92400e',
    tag: '10 ADS',
    unlockType: 'ads',
    adsRequired: 10,
    snakeStyle: 'steampunk',
    headIcon: '⚙️',
    patternType: 'gears',
    eyeColor: '#fbbf24',
    tongueColor: '#ea580c',
    bgBiome: 'steampunk',
    rarity: 'Legendary',
    eyeCount: 2,
    bodyThickness: 'regular',
  },
  {
    id: 'bone',
    name: 'Skeleton Bone Naga 💀',
    price: 0,
    description: 'Ancient undead serpent of polished ivory vertebrae with glowing phantom eyes.',
    bodyGradient: 'from-slate-100 via-stone-300 to-slate-400',
    glowColor: 'rgba(52, 211, 153, 0.7)',
    iconColor: '#10b981',
    accentColor: '#e2e8f0',
    secondaryColor: '#334155',
    previewColor: '#94a3b8',
    tag: '10 ADS',
    unlockType: 'ads',
    adsRequired: 10,
    snakeStyle: 'bone',
    headIcon: '💀',
    patternType: 'bones',
    eyeColor: '#10b981',
    tongueColor: '#34d399',
    bgBiome: 'abyss',
    rarity: 'Legendary',
    eyeCount: 2,
    bodyThickness: 'slender',
  },
  {
    id: 'rainbow',
    name: 'Prismatic Rainbow Serpent 🌈',
    price: 0,
    description: 'Mythical dreamtime feathered serpent shimmering through the entire chromatic spectrum.',
    bodyGradient: 'from-rose-500 via-amber-400 via-emerald-400 via-sky-400 to-purple-500',
    glowColor: 'rgba(244, 114, 182, 0.8)',
    iconColor: '#ffffff',
    accentColor: '#ec4899',
    secondaryColor: '#8b5cf6',
    previewColor: '#ec4899',
    tag: '10 ADS',
    unlockType: 'ads',
    adsRequired: 10,
    snakeStyle: 'rainbow',
    headIcon: '🌈',
    patternType: 'scales',
    eyeColor: '#fef08a',
    tongueColor: '#ec4899',
    bgBiome: 'jungle',
    rarity: 'Mythic',
    eyeCount: 2,
    bodyThickness: 'thick',
  },
  {
    id: 'phoenix',
    name: 'Solar Phoenix Serpent ☀️',
    price: 0,
    description: 'Immortal celestial serpent born from the heart of a sunburst with winged solar plumage.',
    bodyGradient: 'from-yellow-300 via-amber-500 to-red-600',
    glowColor: 'rgba(251, 191, 36, 0.95)',
    iconColor: '#ffffff',
    accentColor: '#f59e0b',
    secondaryColor: '#ef4444',
    previewColor: '#b45309',
    tag: '10 ADS',
    unlockType: 'ads',
    adsRequired: 10,
    snakeStyle: 'phoenix',
    headIcon: '☀️',
    patternType: 'flames',
    eyeColor: '#ffffff',
    tongueColor: '#facc15',
    bgBiome: 'volcano',
    rarity: 'Mythic',
    eyeCount: 2,
    bodyThickness: 'regular',
  },
];

export const TRAIL_VFYS: TrailVfx[] = [
  {
    id: 'sparks',
    name: 'Electric Sparks ⚡',
    price: 0,
    description: 'Bright kinetic electric sparks on arrow release.',
    particleColors: ['#38bdf8', '#60a5fa', '#93c5fd', '#ffffff'],
    type: 'sparks',
  },
  {
    id: 'fire',
    name: 'Blazing Embers 🔥',
    price: 200,
    description: 'Fiery glowing embers and thermal heat sparks.',
    particleColors: ['#f97316', '#ef4444', '#facc15', '#ffffff'],
    type: 'fire',
  },
  {
    id: 'frost',
    name: 'Ice Flurries ❄️',
    price: 250,
    description: 'Crystalline ice snowflakes and frost burst.',
    particleColors: ['#22d3ee', '#67e8f9', '#a5f3fc', '#ffffff'],
    type: 'frost',
  },
  {
    id: 'nebula',
    name: 'Cosmic Stardust 🌌',
    price: 350,
    description: 'Twinkling galactic stardust nebula particles.',
    particleColors: ['#d946ef', '#a855f7', '#818cf8', '#ffffff'],
    type: 'nebula',
  },
  {
    id: 'rainbow',
    name: 'Rainbow Stream 🌈',
    price: 500,
    description: 'Vibrant kaleidoscope particles of every hue.',
    particleColors: ['#ef4444', '#f59e0b', '#10b981', '#06b6d4', '#8b5cf6', '#ec4899'],
    type: 'rainbow',
  },
  {
    id: 'blossom',
    name: 'Sakura Petals 🌸',
    price: 320,
    description: 'Soft pink cherry blossom petals drifting gracefully.',
    particleColors: ['#f472b6', '#fb7185', '#fda4af', '#fdf2f8'],
    type: 'blossom',
  },
  {
    id: 'lightning',
    name: 'Plasma Arcs ⚡',
    price: 400,
    description: 'Crackling high-voltage yellow and blue plasma discharge.',
    particleColors: ['#facc15', '#eab308', '#38bdf8', '#ffffff'],
    type: 'lightning',
  },
  {
    id: 'bubbles',
    name: 'Ocean Bubbles 🫧',
    price: 300,
    description: 'Glittering aquatic bubbles rising to the surface.',
    particleColors: ['#67e8f9', '#38bdf8', '#0284c7', '#ffffff'],
    type: 'bubbles',
  },
  {
    id: 'gold',
    name: 'Gold Coins 🪙',
    price: 450,
    description: 'Shimmering 24k gold treasure flakes and stars.',
    particleColors: ['#fbbf24', '#f59e0b', '#d97706', '#fef08a'],
    type: 'gold',
  },
  {
    id: 'hearts',
    name: 'Love Hearts 💖',
    price: 380,
    description: 'Adorable floating pink and crimson affection hearts.',
    particleColors: ['#ec4899', '#f43f5e', '#fb7185', '#ffffff'],
    type: 'hearts',
  },
];

export function getDirectionVector(dir: string): { dx: number; dy: number } {
  switch (dir) {
    case 'up': return { dx: 0, dy: -1 };
    case 'down': return { dx: 0, dy: 1 };
    case 'left': return { dx: -1, dy: 0 };
    case 'right': return { dx: 1, dy: 0 };
    case 'up-right': return { dx: 1, dy: -1 };
    case 'up-left': return { dx: -1, dy: -1 };
    case 'down-right': return { dx: 1, dy: 1 };
    case 'down-left': return { dx: -1, dy: 1 };
    default: return { dx: 0, dy: -1 };
  }
}

export function getRotationForDirection(dir: string): number {
  switch (dir) {
    case 'up': return 0;
    case 'up-right': return 45;
    case 'right': return 90;
    case 'down-right': return 135;
    case 'down': return 180;
    case 'down-left': return 225;
    case 'left': return 270;
    case 'up-left': return 315;
    default: return 0;
  }
}
